// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSJDYlnlLsZOKb4j9jhuixD7_VVKEoicE',
    appId: '1:442036078735:web:d0b80c1610fe16ab4148fa',
    messagingSenderId: '442036078735',
    projectId: 'carvo-eb283',
    authDomain: 'carvo-eb283.firebaseapp.com',
    storageBucket: 'carvo-eb283.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmNLeSVsZrAC9WljPatWFt036gFSsnnIM',
    appId: '1:442036078735:android:88bbd03d7a6559414148fa',
    messagingSenderId: '442036078735',
    projectId: 'carvo-eb283',
    storageBucket: 'carvo-eb283.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1rtqDp7hGKs6LFDdLgO4CSKVFmZByapY',
    appId: '1:442036078735:ios:186c606ec8add1854148fa',
    messagingSenderId: '442036078735',
    projectId: 'carvo-eb283',
    storageBucket: 'carvo-eb283.firebasestorage.app',
    iosBundleId: 'com.example.cravo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1rtqDp7hGKs6LFDdLgO4CSKVFmZByapY',
    appId: '1:442036078735:ios:186c606ec8add1854148fa',
    messagingSenderId: '442036078735',
    projectId: 'carvo-eb283',
    storageBucket: 'carvo-eb283.firebasestorage.app',
    iosBundleId: 'com.example.cravo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSJDYlnlLsZOKb4j9jhuixD7_VVKEoicE',
    appId: '1:442036078735:web:5011246bcd8a36e94148fa',
    messagingSenderId: '442036078735',
    projectId: 'carvo-eb283',
    authDomain: 'carvo-eb283.firebaseapp.com',
    storageBucket: 'carvo-eb283.firebasestorage.app',
  );
}
